Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/03/2023
Var
n,i:inteiro


Inicio
escreval ("Digite um número de 1 a 10")
Leia(n)
se n<=10 então
para i de 1 até 10 faça
escreval(n,"x",i,"=", n*i)
fimpara
senão
escreval("número inválido")
fimse



Fimalgoritmo