Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/03/2023
Var

r,i1,i2:real


Inicio
escreval("Digite uma idade:")
leia(i1)
escreval("Digite outra idade:")
leia(i2)
r<-(i1+i2)/2
escreval ("a média é:",r)


Fimalgoritmo