Algoritmo "Trabalho 2"

Var
Lado1,Lado2,Lado3: real


Inicio
escreval ("Digite os valores do triângulo")
leia (Lado1,Lado2,Lado3)

se (Lado1+Lado2)<Lado3  então
escreval ("não é um triangulo")
senão
se(Lado1=Lado2) e (Lado2=Lado3)então
escreval ("seu triangulo é equilátero")
senão
se (Lado1=Lado2) e (Lado1 <> Lado3) então
escreval("Isóciles")
senão
escreval("Escaleno")
fimse
fimse
fimse


 
Fimalgoritmo


